// flow-typed signature: 309bfd47626cca24cd5b55f8f43eaa8a
// flow-typed version: <<STUB>>/graphql-tools_v^2.23.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-tools/dist/index' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/Interfaces' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/isEmptyObject' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/Logger' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/mergeDeep' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/mock' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/schemaGenerator' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/schemaVisitor' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/defaultMergedResolver' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/delegateToSchema' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/errors' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/index' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/introspectSchema' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/linkToFetcher' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/makeRemoteExecutableSchema' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/mergeSchemas' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/observableToAsyncIterable' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/resolveFromParentTypename' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/schemaRecreation' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/typeFromAST' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/stitching/TypeRegistry' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-tools/dist/index.js' {
  declare module.exports: $Exports<'graphql-tools/dist/index'>;
}
declare module 'graphql-tools/dist/Interfaces.js' {
  declare module.exports: $Exports<'graphql-tools/dist/Interfaces'>;
}
declare module 'graphql-tools/dist/isEmptyObject.js' {
  declare module.exports: $Exports<'graphql-tools/dist/isEmptyObject'>;
}
declare module 'graphql-tools/dist/Logger.js' {
  declare module.exports: $Exports<'graphql-tools/dist/Logger'>;
}
declare module 'graphql-tools/dist/mergeDeep.js' {
  declare module.exports: $Exports<'graphql-tools/dist/mergeDeep'>;
}
declare module 'graphql-tools/dist/mock.js' {
  declare module.exports: $Exports<'graphql-tools/dist/mock'>;
}
declare module 'graphql-tools/dist/schemaGenerator.js' {
  declare module.exports: $Exports<'graphql-tools/dist/schemaGenerator'>;
}
declare module 'graphql-tools/dist/schemaVisitor.js' {
  declare module.exports: $Exports<'graphql-tools/dist/schemaVisitor'>;
}
declare module 'graphql-tools/dist/stitching/defaultMergedResolver.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/defaultMergedResolver'>;
}
declare module 'graphql-tools/dist/stitching/delegateToSchema.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/delegateToSchema'>;
}
declare module 'graphql-tools/dist/stitching/errors.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/errors'>;
}
declare module 'graphql-tools/dist/stitching/index.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/index'>;
}
declare module 'graphql-tools/dist/stitching/introspectSchema.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/introspectSchema'>;
}
declare module 'graphql-tools/dist/stitching/linkToFetcher.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/linkToFetcher'>;
}
declare module 'graphql-tools/dist/stitching/makeRemoteExecutableSchema.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/makeRemoteExecutableSchema'>;
}
declare module 'graphql-tools/dist/stitching/mergeSchemas.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/mergeSchemas'>;
}
declare module 'graphql-tools/dist/stitching/observableToAsyncIterable.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/observableToAsyncIterable'>;
}
declare module 'graphql-tools/dist/stitching/resolveFromParentTypename.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/resolveFromParentTypename'>;
}
declare module 'graphql-tools/dist/stitching/schemaRecreation.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/schemaRecreation'>;
}
declare module 'graphql-tools/dist/stitching/typeFromAST.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/typeFromAST'>;
}
declare module 'graphql-tools/dist/stitching/TypeRegistry.js' {
  declare module.exports: $Exports<'graphql-tools/dist/stitching/TypeRegistry'>;
}
