// flow-typed signature: 147b2cecaea1fbe8be7f54c1349cba2a
// flow-typed version: <<STUB>>/lerna_v^3.0.0-beta.19/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lerna'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lerna' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lerna/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lerna/cli.js' {
  declare module.exports: $Exports<'lerna/cli'>;
}
